version: "3.8"
services:
  easycrit-frontend:
    container_name: easycrit-frontend
    image: easycrit
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "${FRONTEND_PORT}:3000"
